### ISSUE TITLE
Identify Subset of PCAWG Donors for Upload

### ISSUE THREAD

**Issue by b-f-chan** [EUCANCan-Federated-Data-Portal/metadata-schemas#4]
- Just use large download file from ICGC25K with all PCAWG donors
- 10 donors per node (3 x 10)
    - 60 files (2 VCFs each, 1 for SNP, 1 for InDel)
- We would load the Toronto node; but we might have access to load the other two nodes ourselves
- Choose from multiple projects
- A few different primary sites
- Genes
    - Bio types
    - GO
    - Cancer Gene Census
- Mutations
    - Consequence Types
    - Variant Classes
    - Functional Impacts

Question: What is Song base schema for DMS and will it be an issue?  DMS is running v.4.5.0 --> Test base schema off Swagger UI

**Expected Output:** List of 30 donors and their associated SNP + Indel VCF files extracted from the aggregated PCAWG set downloaded from ICGC25K

**Comment by lindaxiang** [comment]
@b-f-chan  I've added the selected donors and associated snv_mnv + indel raw VCF files to the google drive, here are the links:
- [donor_list_selected30](https://drive.google.com/file/d/1DgDWvKvsHzh2no53rxF-zNJ53-HCY6Mq/view?usp=share_link)
- [pcawg_consensus_indel_selected30](https://drive.google.com/drive/folders/1QgVWeoALtA0LklZZQ55ngkDhLr2zS8vr?usp=share_link)
- [pcawg_consensus_snv_mnv_selected30](https://drive.google.com/drive/folders/1IagFKhgFOaz_2H-EnRpDoIxD0RBgrB7P?usp=share_link)

**Comment by b-f-chan** [comment]
Subset identified and used to generate payloads for the 3 prod nodes, closing
