### ISSUE TITLE
Prepare Annotated VCFs for Ingestion by EUCANCan Toronto Node

### ISSUE THREAD

**Issue by b-f-chan** [EUCANCan-Federated-Data-Portal/metadata-schemas#5]
Need to prepare the annotated VFCs to be loaded and uses on the EUCANCan Toronto node

**Expected Output:**

- Use the VCFs extracted from ticket #4
- Run them through the VEP workflow, only the step for annotation: https://github.com/nf-core/sarek
- Annotated VCFs will be the final expected outcome

**Comment by lindaxiang** [comment]
@b-f-chan @joneubank the VEP annotated VCFs are added to google drive with the following links:
- [VEP annotated SNV_MNV VCFs](https://drive.google.com/drive/folders/1vU0dqlVD8_4sLYyfxbrkOoAerhL71wkF?usp=share_link)
- [VEP annotated InDel VCFs](https://drive.google.com/drive/folders/1H0dCY1I9BUrvtfiPjB65PD-mVRsIh-UJ?usp=share_link)

**Comment by b-f-chan** [comment]
VCFs prepared and used to upload to Toronto prod node, closing
