### ISSUE TITLE
Generate 60 File-Centric (VCF) Payloads for EUCANCan Song

### ISSUE THREAD

**Issue by b-f-chan** [EUCANCan-Federated-Data-Portal/metadata-schemas#7]
Need to generate 60 file-centric (VCF) payloads for the EUCANCan Song

30 for Indel + 30 for SNV

- [ ] (1) Populate with minimum required data for the core clinical entities:

- Donor
- Sample
- Specimen
- Primary Diagnosis
- Treatment
- Follow-up

Assume 1 sample per donor (tumour only but include matched normal ID though it won't link to anything concrete)

- [ ] (2) Add file properties to the payloads (e.g. file type, file size, md5sum, etc.)

- [ ] (3) Add workflow properties to payloads

- [ ] (4) Add experiment properties to payloads

**Comment by lindaxiang** [comment]
@edsu7 @b-f-chan 

For the payloads:
- `sampleId/specimenId/donorId` should be removed under `samples` section
- `info` field can be added to each file under `file` section as
```
"info": {
  "data_category": "Simple Nucleotide Variation"
}
```

**Comment by edsu7** [comment]
Updated payloads. Added `info` under `files` and removed ARGO ids from `samples`

**Comment by b-f-chan** [comment]
Payloads generated and reviewed, first 20 uploaded to Toronto node, closing
